// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsqM3eJnPc68YEh-IbjYiJSJ5BlovXciU',
    appId: '1:402214942879:web:2f2ce012fe4d2752314aaa',
    messagingSenderId: '402214942879',
    projectId: 'vault-sec',
    authDomain: 'vault-sec.firebaseapp.com',
    storageBucket: 'vault-sec.firebasestorage.app',
    measurementId: 'G-BS183NBBL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYhvraAnQV-gRNJtQa_yvtuE0LSbXNesk',
    appId: '1:402214942879:android:cf5ad76ffbf6a3aa314aaa',
    messagingSenderId: '402214942879',
    projectId: 'vault-sec',
    storageBucket: 'vault-sec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAduaPLWmP3Lm99FU3s3vUcOp-e_kOyYhs',
    appId: '1:402214942879:ios:0714283d2f46c64f314aaa',
    messagingSenderId: '402214942879',
    projectId: 'vault-sec',
    storageBucket: 'vault-sec.firebasestorage.app',
    iosBundleId: 'com.thecraftycoders.secureVault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAduaPLWmP3Lm99FU3s3vUcOp-e_kOyYhs',
    appId: '1:402214942879:ios:0714283d2f46c64f314aaa',
    messagingSenderId: '402214942879',
    projectId: 'vault-sec',
    storageBucket: 'vault-sec.firebasestorage.app',
    iosBundleId: 'com.thecraftycoders.secureVault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsqM3eJnPc68YEh-IbjYiJSJ5BlovXciU',
    appId: '1:402214942879:web:aa5e476c2f128ed5314aaa',
    messagingSenderId: '402214942879',
    projectId: 'vault-sec',
    authDomain: 'vault-sec.firebaseapp.com',
    storageBucket: 'vault-sec.firebasestorage.app',
    measurementId: 'G-LZ7746FBV6',
  );
}
